// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectosConstruccion.Persistencia.DataContext;

namespace ProyectosConstruccion.Persistencia.Migrations
{
    [DbContext(typeof(proyectoconstruccionContext))]
    partial class proyectoconstruccionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Compra", b =>
                {
                    b.Property<short>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(6)")
                        .HasColumnName("ID_Compra");

                    b.Property<byte?>("Cantidad")
                        .HasColumnType("tinyint(4)");

                    b.Property<string>("Fecha")
                        .HasMaxLength(0)
                        .HasColumnType("varchar(0)");

                    b.Property<byte?>("IdMaterialConstruccion")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ID_MaterialConstruccion");

                    b.Property<short?>("IdProyecto")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("ID_Proyecto");

                    b.Property<string>("Pagado")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("IdCompra")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMaterialConstruccion" }, "compra_materialconstruccion_fk");

                    b.HasIndex(new[] { "IdProyecto" }, "compra_proyecto_fk");

                    b.ToTable("compra");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Lider", b =>
                {
                    b.Property<byte>("IdLider")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ID_Lider");

                    b.Property<string>("Cargo")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("CiudadResidencia")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Ciudad_Residencia");

                    b.Property<decimal?>("Clasificacion")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("Documento_Identidad");

                    b.Property<string>("FechaNacimiento")
                        .HasMaxLength(0)
                        .HasColumnType("varchar(0)")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("Primer_Apellido");

                    b.Property<int?>("Salario")
                        .HasColumnType("mediumint(9)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("Segundo_Apellido");

                    b.HasKey("IdLider")
                        .HasName("PRIMARY");

                    b.ToTable("lider");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Materialconstruccion", b =>
                {
                    b.Property<byte>("IdMaterialConstruccion")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ID_MaterialConstruccion");

                    b.Property<string>("Importado")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("NombreMaterial")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("Nombre_Material");

                    b.Property<short?>("PrecioUnidad")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("Precio_Unidad");

                    b.HasKey("IdMaterialConstruccion")
                        .HasName("PRIMARY");

                    b.ToTable("materialconstruccion");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Proyecto", b =>
                {
                    b.Property<short>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(6)")
                        .HasColumnName("ID_Proyecto");

                    b.Property<string>("Acabados")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("BancoVinculado")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("Banco_Vinculado");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Clasificacion")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Constructora")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("FechaInicio")
                        .HasMaxLength(0)
                        .HasColumnType("varchar(0)")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<byte?>("IdLider")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ID_Lider");

                    b.Property<byte?>("IdTipo")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ID_Tipo");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("NumeroBanos")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("Numero_Banos");

                    b.Property<decimal?>("NumeroHabitaciones")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("Numero_Habitaciones");

                    b.Property<decimal?>("PorcentajeCuotaInicial")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("Porcentaje_Cuota_Inicial");

                    b.Property<string>("Serial")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.HasKey("IdProyecto")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdLider" }, "proyecto_lider_fk");

                    b.HasIndex(new[] { "IdTipo" }, "proyecto_tipo_fk");

                    b.ToTable("proyecto");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Tipo", b =>
                {
                    b.Property<byte>("IdTipo")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("ID_Tipo");

                    b.Property<short?>("AreaMax")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("Area_Max");

                    b.Property<short?>("CodigoTipo")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("Codigo_Tipo");

                    b.Property<byte?>("Estrato")
                        .HasColumnType("tinyint(4)");

                    b.Property<byte?>("Financiable")
                        .HasColumnType("tinyint(4)");

                    b.HasKey("IdTipo")
                        .HasName("PRIMARY");

                    b.ToTable("tipo");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Compra", b =>
                {
                    b.HasOne("ProyectosConstruccion.Persistencia.Models.Materialconstruccion", "IdMaterialConstruccionNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdMaterialConstruccion")
                        .HasConstraintName("compra_materialconstruccion_fk");

                    b.HasOne("ProyectosConstruccion.Persistencia.Models.Proyecto", "IdProyectoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProyecto")
                        .HasConstraintName("compra_proyecto_fk");

                    b.Navigation("IdMaterialConstruccionNavigation");

                    b.Navigation("IdProyectoNavigation");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Proyecto", b =>
                {
                    b.HasOne("ProyectosConstruccion.Persistencia.Models.Lider", "IdLiderNavigation")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdLider")
                        .HasConstraintName("proyecto_lider_fk");

                    b.HasOne("ProyectosConstruccion.Persistencia.Models.Tipo", "IdTipoNavigation")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdTipo")
                        .HasConstraintName("proyecto_tipo_fk");

                    b.Navigation("IdLiderNavigation");

                    b.Navigation("IdTipoNavigation");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Lider", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Materialconstruccion", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Proyecto", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("ProyectosConstruccion.Persistencia.Models.Tipo", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
